# Generated by Django 4.1.5 on 2023-01-28 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakRole',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keycloak_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KeycloakGroup',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keycloak_id', models.CharField(blank=True, max_length=36, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keycloak_group', to='keycloak_auth.keycloakgroup')),
                ('roles', models.ManyToManyField(blank=True, to='keycloak_auth.keycloakrole')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wiki', models.URLField(blank=True, null=True)),
                ('cloud', models.URLField(blank=True, null=True)),
                ('keycloak_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='keycloak_auth.keycloakgroup')),
            ],
        ),
    ]
