# Generated by Django 4.1.2 on 2022-11-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakgroup',
            name='keycloak_id',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='keycloakgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keycloak_group', to='keycloak_auth.keycloakgroup'),
        ),
    ]
