# Generated by Django 4.1.5 on 2023-02-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keycloakgroup',
            name='roles',
        ),
        migrations.AddField(
            model_name='keycloakgroup',
            name='membership_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='KeycloakRole',
        ),
    ]
