# Generated by Django 4.1.5 on 2023-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0002_remove_keycloakgroup_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keycloakgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
