# Generated by Django 4.1.3 on 2022-11-23 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0002_alter_keycloakgroup_keycloak_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakgroup',
            name='keycloak_id',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='keycloakgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keycloak_group', to='keycloak_auth.keycloakgroup'),
        ),
    ]
