# Generated by Django 4.1.5 on 2023-01-28 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0003_alter_keycloakgroup_keycloak_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wiki', models.URLField(blank=True, null=True)),
                ('cloud', models.URLField(blank=True, null=True)),
                ('keycloak_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='keycloak_auth.keycloakgroup')),
            ],
        ),
    ]
