# Generated by Django 4.1.7 on 2023-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0003_keycloakgroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycloakgroup',
            name='membership_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
