# Generated by Django 4.1.8 on 2023-04-23 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0004_alter_keycloakgroup_membership_allowed'),
        ('basic', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='group_registration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='group_registration_level',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invitation_code',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invitation_code_group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invitation_code_single',
        ),
        migrations.RemoveField(
            model_name='event',
            name='limited_registration_hierarchy',
        ),
        migrations.RemoveField(
            model_name='event',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='personal_data_required',
        ),
        migrations.RemoveField(
            model_name='event',
            name='single_registration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='single_registration_level',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.AddField(
            model_name='event',
            name='inviting_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inviting_group', to='keycloak_auth.keycloakgroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_level',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='basic.scoutorgalevel'),
        ),
        migrations.AddField(
            model_name='event',
            name='invited_groups',
            field=models.ManyToManyField(blank=True, related_name='invited_groups', to='keycloak_auth.keycloakgroup'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='keycloak_admin_path',
        ),
        migrations.RemoveField(
            model_name='event',
            name='keycloak_path',
        ),
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_planer_modules',
        ),
        migrations.RemoveField(
            model_name='standardeventtemplate',
            name='planer_modules',
        ),
        migrations.DeleteModel(
            name='EventPlanerModule',
        ),
        migrations.AddField(
            model_name='event',
            name='admin_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_group', to='keycloak_auth.keycloakgroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='view_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_group', to='keycloak_auth.keycloakgroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_possible_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='event.eventlocation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_possible_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.eventlocation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='single',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_accepted',
        ),
    ]
