# Generated by Django 4.1.8 on 2023-04-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_group_registration_and_more_squashed_0011_remove_registration_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationparticipant',
            name='deactivated',
        ),
        migrations.RemoveField(
            model_name='registrationparticipant',
            name='needs_confirmation',
        ),
        migrations.RemoveField(
            model_name='standardeventtemplate',
            name='event',
        ),
    ]
