# Generated by Django 4.1.8 on 2023-04-25 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_remove_registrationparticipant_deactivated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodulemapper',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
