# Generated by Django 4.1.8 on 2023-04-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_eventmodulemapper_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardeventtemplate',
            name='personal_registration',
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='event.eventmodulemapper'),
        ),
    ]
