# Generated by Django 4.1.8 on 2023-04-25 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_remove_standardeventtemplate_personal_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardeventtemplate',
            name='registration',
        ),
        migrations.AddField(
            model_name='standardeventtemplate',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='event.eventmodulemapper'),
        ),
    ]
