# Generated by Django 4.1.8 on 2023-04-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_standardeventtemplate_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeeventmodulemapper',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='registrationparticipant',
            name='allow_permanently',
        ),
    ]
