# Generated by Django 4.1.8 on 2023-04-30 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_remove_attributeeventmodulemapper_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodule',
            name='custom',
        ),
        migrations.AddField(
            model_name='eventmodule',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='eventmodule',
            name='ordering',
            field=models.IntegerField(auto_created=True, default=999),
        ),
        migrations.AddField(
            model_name='eventmodule',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodule',
            name='standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='introduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduction', to='event.eventmodule'),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter', to='event.eventmodule'),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='other_optional_modules',
            field=models.ManyToManyField(blank=True, related_name='other_optional_modules', to='event.eventmodule'),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='other_required_modules',
            field=models.ManyToManyField(blank=True, related_name='other_required_modules', to='event.eventmodule'),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='event.eventmodule'),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation', to='event.eventmodule'),
        ),
        migrations.DeleteModel(
            name='EventModuleMapper',
        ),
    ]
