# Generated by Django 4.1.8 on 2023-04-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_remove_eventmodule_custom_eventmodule_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodule',
            name='type',
        ),
    ]
