# Generated by Django 4.1.8 on 2023-05-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_remove_eventmodule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='introduction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='introduction', to='event.eventmodule'),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='letter', to='event.eventmodule'),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='event.eventmodule'),
        ),
        migrations.AlterField(
            model_name='standardeventtemplate',
            name='summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='event.eventmodule'),
        ),
    ]
