# Generated by Django 4.1.8 on 2023-05-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_alter_standardeventtemplate_introduction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttributeEventModuleMapper',
        ),
    ]
