# Generated by Django 4.1.8 on 2023-05-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_delete_attributeeventmodulemapper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='responsible_persons',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='scout_organisation',
        ),
        migrations.RemoveField(
            model_name='registrationparticipant',
            name='booking_option',
        ),
        migrations.RemoveField(
            model_name='registrationparticipant',
            name='eat_habit',
        ),
        migrations.RemoveField(
            model_name='registrationparticipant',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='registrationparticipant',
            name='scout_group',
        ),
        migrations.RemoveField(
            model_name='registrationparticipant',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='workshopparticipant',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='workshopparticipant',
            name='workshop',
        ),
    ]
