# Generated by Django 4.1.8 on 2023-05-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_remove_standardeventtemplate_other_optional_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodule',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
