# Generated by Django 4.2.2 on 2023-06-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_eventmodule_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlocation',
            name='tags',
        ),
    ]
