# Generated by Django 4.1.9 on 2023-07-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_eventmodule_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlocation',
            name='tags',
        ),
    ]
