# Generated by Django 4.1.2 on 2022-10-17 09:29

import backend.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTemplate',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=backend.storage_backends.FileTemplateMediaStorage, upload_to='')),
                ('type', models.CharField(choices=[('K', 'KJP Liste'), ('I', 'Rechnungserstellung Felix'), ('P', 'Teilnehmerliste'), ('A', 'Attributliste'), ('T', 'Anreise Matrix'), ('j', 'KJR Liste')], default='K', max_length=1)),
                ('extension', models.CharField(choices=[('E', 'Excel'), ('P', 'PDF')], default='E', max_length=1)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedFiles',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=backend.storage_backends.GeneratedFilesStorage, upload_to='')),
                ('error_msg', models.CharField(blank=True, max_length=10000, null=True)),
                ('status', models.CharField(choices=[('Q', 'In der Warteschlange.'), ('P', 'Dokument wird erstellt.'), ('FS', 'Dokument erfolgreich erstellt.'), ('FF', 'Dokumenten Erstellung Fehlgeschlagen.')], default='Q', max_length=2)),
                ('extension', models.CharField(choices=[('E', 'Excel'), ('P', 'PDF')], default='E', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_generator.filetemplate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
