# Generated by Django 4.1.9 on 2023-06-07 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_eathabit_public'),
        ('file_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedfiles',
            name='bund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic.scouthierarchy'),
        ),
        migrations.AlterField(
            model_name='filetemplate',
            name='extension',
            field=models.CharField(choices=[('E', 'Excel')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='generatedfiles',
            name='error_msg',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='generatedfiles',
            name='extension',
            field=models.CharField(choices=[('E', 'Excel')], default='E', max_length=1),
        ),
    ]
