# Generated by Django 4.1.5 on 2023-01-28 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashIncome',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('transfer_subject', models.CharField(blank=True, max_length=250)),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('transfer_reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
