# Generated by Django 4.1.8 on 2023-05-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('cash', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashincome',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.registration'),
        ),
    ]
