# Generated by Django 4.1.5 on 2023-06-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash", "0003_alter_cashincome_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashincome",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
