# Generated by Django 4.1.8 on 2023-05-04 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0021_remove_registration_event_and_more'),
        ('basic', '0002_eathabit_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('responsible_persons', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('scout_organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.scouthierarchy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('scout_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(default='Generated', max_length=100)),
                ('last_name', models.CharField(default='Generated', max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Männlich'), ('F', 'Weiblich'), ('D', 'Divers'), ('N', 'Keine Angabe')], default='N', max_length=1)),
                ('generated', models.BooleanField(default=False)),
                ('leader', models.CharField(choices=[('N', 'Kein Amt'), ('DPVFue', 'DPV-Führung'), ('BuFue', 'Bundesführung'), ('RinFue', 'Ringführung'), ('StaFue', 'Stammesführung'), ('SiFue', 'Sippenführung'), ('RoFue', 'Roverrundenführung'), ('MeuFue', 'Meutenführung')], default='N', max_length=6)),
                ('scout_level', models.CharField(choices=[('N', 'Unbekannt'), ('W', 'Wölfling'), ('S', 'Sippling'), ('R', 'Rover_Innen')], default='N', max_length=6)),
                ('booking_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.bookingoption')),
                ('eat_habit', models.ManyToManyField(blank=True, to='basic.eathabit')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
                ('scout_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.scouthierarchy')),
                ('zip_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.zipcode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
