# Generated by Django 4.1.5 on 2023-05-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_person_edited_last"),
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationparticipant",
            old_name="street",
            new_name="address",
        ),
        migrations.AddField(
            model_name="registrationparticipant",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="authentication.person",
            ),
        ),
    ]
