# Generated by Django 4.2.2 on 2023-06-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_street_registrationparticipant_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
            ],
        ),
    ]
