# Generated by Django 4.2.11 on 2025-03-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registrationrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationparticipant',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrationparticipant',
            name='scout_function',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationparticipant',
            name='scout_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
