# Generated by Django 4.1.5 on 2023-01-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestgroupaccess',
            old_name='text',
            new_name='application_text',
        ),
        migrations.AddField(
            model_name='requestgroupaccess',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
