# Generated by Django 4.1.5 on 2023-02-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_rename_text_requestgroupaccess_application_text_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestgroupaccess",
            name="status",
            field=models.CharField(
                choices=[
                    ("nothing", "offen"),
                    ("accepted", "akzeptiert"),
                    ("declined", "abgelehnt"),
                ],
                default="nothing",
                max_length=8,
            ),
        ),
    ]
