# Generated by Django 4.1.7 on 2023-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_requestgroupaccess_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_notification',
            field=models.CharField(choices=[('Full', 'Alles'), ('3H', 'Alle 3 Stunden'), ('12H', 'Alle 12 Stunden'), ('Daily', 'Täglich'), ('Weekly', 'Wöchentlich'), ('Important', 'Nur wichtiges')], default='Full', max_length=10),
        ),
    ]
