# Generated by Django 4.1.2 on 2022-10-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dsgvo_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
