# Generated by Django 4.1.2 on 2022-10-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_dsgvo_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='keycloak_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
