# Generated by Django 4.1.2 on 2022-10-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_keycloak_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='leader',
            field=models.CharField(choices=[('N', 'Kein Amt'), ('DPVFue', 'DPV-Führung'), ('BuFue', 'Bundesführung'), ('RinFue', 'Ringführung'), ('StaFue', 'Stammesführung'), ('SiFue', 'Sippenführung'), ('RoFue', 'Roverrundenführung'), ('MeuFue', 'Meutenführung')], default='N', max_length=6),
        ),
    ]
