# Generated by Django 4.1.3 on 2022-11-06 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0002_alter_keycloakgroup_keycloak_id_and_more'),
        ('authentication', '0009_alter_person_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestGroupAccess',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('nothing', 'Keine Auwahl'), ('accepted', 'Akzeptiert'), ('declined', 'Abgelehnt')], default='nothing', max_length=8)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_by', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keycloak_auth.keycloakgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
