# Generated by Django 4.1.3 on 2022-11-04 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_requestgroupaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestgroupaccess',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
