# Generated by Django 4.1.3 on 2022-11-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0002_alter_keycloakgroup_keycloak_id_and_more'),
        ('authentication', '0010_requestgroupaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestgroupaccess',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keycloak_auth.keycloakgroup'),
        ),
    ]
