# Generated by Django 4.1.3 on 2022-11-11 13:40

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_customuser_keycloak_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(editable=False, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterField(
            model_name='requestgroupaccess',
            name='status',
            field=models.CharField(choices=[('nothing', 'Nicht überprüft'), ('accepted', 'Akzeptiert'), ('declined', 'Abgelehnt')], default='nothing', max_length=8),
        ),
    ]
