# Generated by Django 4.1.3 on 2022-11-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='scout_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='scout_organisation',
        ),
    ]
