# Generated by Django 4.1.3 on 2022-11-12 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
