# Generated by Django 4.1.3 on 2022-11-23 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_person_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='keycloak_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ManyToManyField(blank=True, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
