# Generated by Django 4.1.5 on 2023-01-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_customuser_keycloak_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='keycloak_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
