# Generated by Django 4.1.5 on 2023-01-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_customuser_keycloak_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestgroupaccess',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
