# Generated by Django 4.1.5 on 2023-02-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
