# Generated by Django 4.1.5 on 2023-02-11 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("keycloak_auth", "0003_keycloakgroup_description"),
        ("messaging", "0004_alter_message_created_by_alter_message_supervisor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "created_by_name",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "created_by_email",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("urgent", "Eilig"), ("normal", "normal")],
                        default="normal",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Ungelesen"),
                            ("WIP", "In Arbeit"),
                            ("success", "Erfolgreich"),
                            ("failed", "Nicht erfolgreich"),
                        ],
                        default="unread",
                        max_length=30,
                    ),
                ),
                (
                    "issue_subject",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IssueType",
            fields=[
                (
                    "sorting",
                    models.IntegerField(auto_created=True, null=True, unique=True),
                ),
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=30)),
                ("is_public", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=100)),
                (
                    "responsable_groups",
                    models.ManyToManyField(
                        blank=True, to="keycloak_auth.keycloakgroup"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="message",
            old_name="is_processed",
            new_name="has_been_read",
        ),
        migrations.RemoveField(
            model_name="message",
            name="created_by_email",
        ),
        migrations.RemoveField(
            model_name="message",
            name="internal_comment",
        ),
        migrations.RemoveField(
            model_name="message",
            name="message_subject",
        ),
        migrations.RemoveField(
            model_name="message",
            name="message_type",
        ),
        migrations.RemoveField(
            model_name="message",
            name="supervisor",
        ),
        migrations.AddField(
            model_name="message",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="message_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="MessageType",
        ),
        migrations.AddField(
            model_name="issue",
            name="issue_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="messaging.issuetype"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="processors",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="message",
            name="issue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issue",
                to="messaging.issue",
            ),
        ),
    ]
