# Generated by Django 4.1.5 on 2023-02-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_issue_issuetype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("unread", "Ungelesen"),
                    ("wip", "In Arbeit"),
                    ("success", "Erfolgreich"),
                    ("failed", "Nicht erfolgreich"),
                ],
                default="unread",
                max_length=30,
            ),
        ),
    ]
