# Generated by Django 4.1.5 on 2023-01-28 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('template', models.BooleanField(default=False)),
                ('template_id', models.IntegerField(default=-1)),
                ('in_summary', models.BooleanField(default=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.tagtype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AttributeDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('header', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BooleanAttribute',
            fields=[
                ('abstractattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.abstractattribute')),
                ('boolean_field', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('attributes.abstractattribute',),
        ),
        migrations.CreateModel(
            name='FloatAttribute',
            fields=[
                ('abstractattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.abstractattribute')),
                ('float_field', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('attributes.abstractattribute',),
        ),
        migrations.CreateModel(
            name='IntegerAttribute',
            fields=[
                ('abstractattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.abstractattribute')),
                ('integer_field', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('attributes.abstractattribute',),
        ),
        migrations.CreateModel(
            name='StringAttribute',
            fields=[
                ('abstractattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.abstractattribute')),
                ('string_field', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('attributes.abstractattribute',),
        ),
        migrations.CreateModel(
            name='TimeAttribute',
            fields=[
                ('abstractattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.abstractattribute')),
                ('date_field', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('attributes.abstractattribute',),
        ),
        migrations.CreateModel(
            name='TravelAttribute',
            fields=[
                ('abstractattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attributes.abstractattribute')),
                ('number_persons', models.IntegerField(default=0)),
                ('type_field', models.CharField(blank=True, choices=[('T', 'Bahn'), ('B', 'Reisebus'), ('C', 'PKW'), ('O', 'Sonstiges')], max_length=1, null=True)),
                ('date_time_field', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('attributes.abstractattribute',),
        ),
    ]
