# Generated by Django 4.1.8 on 2023-05-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0019_alter_standardeventtemplate_introduction_and_more'),
        ('attributes', '0002_remove_abstractattribute_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('in_summary', models.BooleanField(default=True)),
                ('number_persons', models.IntegerField(default=0)),
                ('type_field', models.CharField(blank=True, choices=[('T', 'Bahn'), ('B', 'Reisebus'), ('C', 'PKW'), ('O', 'Sonstiges')], max_length=1, null=True)),
                ('date_time_field', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.registration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('in_summary', models.BooleanField(default=True)),
                ('date_field', models.DateTimeField()),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.registration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StringAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('in_summary', models.BooleanField(default=True)),
                ('string_field', models.TextField(blank=True, max_length=10000, null=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.registration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegerAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('in_summary', models.BooleanField(default=True)),
                ('integer_field', models.IntegerField(default=0)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.registration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloatAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('in_summary', models.BooleanField(default=True)),
                ('float_field', models.FloatField()),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.registration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BooleanAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('in_summary', models.BooleanField(default=True)),
                ('boolean_field', models.BooleanField(default=False)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.registration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
