# Generated by Django 4.1.8 on 2023-05-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeEventModuleMapper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('text', models.CharField(max_length=10000, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('min_length', models.IntegerField(default=0)),
                ('max_length', models.IntegerField(default=0)),
                ('tooltip', models.CharField(blank=True, max_length=1000, null=True)),
                ('default_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('field_type', models.CharField(blank=True, max_length=25, null=True)),
                ('icon', models.CharField(blank=True, max_length=25, null=True)),
                ('max_entries', models.IntegerField(default=1)),
            ],
        ),
    ]
