# Generated by Django 4.1.8 on 2023-05-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_delete_attributeeventmodulemapper'),
        ('attributes', '0004_attributeeventmodulemapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeeventmodulemapper',
            name='event_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventmodule'),
        ),
    ]
