# Generated by Django 4.1.8 on 2023-05-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('attributes', '0005_attributeeventmodulemapper_event_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
        migrations.AlterField(
            model_name='floatattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
        migrations.AlterField(
            model_name='integerattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
        migrations.AlterField(
            model_name='stringattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
        migrations.AlterField(
            model_name='timeattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
        migrations.AlterField(
            model_name='travelattribute',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
    ]
