# Generated by Django 4.1.8 on 2023-05-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0007_rename_attributeeventmodulemapper_attributemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributemodule',
            name='standard',
            field=models.BooleanField(default=False),
        ),
    ]
