# Generated by Django 4.1.8 on 2023-05-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0008_attributemodule_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributemodule',
            name='field_type',
            field=models.CharField(choices=[('BoA', 'BooleanAttribute'), ('TiA', 'TimeAttribute'), ('InA', 'IntegerAttribute'), ('FlA', 'FloatAttribute'), ('StA', 'StringAttribute'), ('TrA', 'TravelAttribute')], default='InA', max_length=3),
        ),
    ]
