# Generated by Django 4.1.8 on 2023-05-05 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0009_alter_attributemodule_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleanattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
        migrations.AddField(
            model_name='floatattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
        migrations.AddField(
            model_name='integerattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
        migrations.AddField(
            model_name='stringattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
        migrations.AddField(
            model_name='timeattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
        migrations.AddField(
            model_name='travelattribute',
            name='attribute_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.attributemodule'),
        ),
    ]
