# Generated by Django 4.1.8 on 2023-05-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0010_booleanattribute_attribute_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleanattribute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='floatattribute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='integerattribute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stringattribute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='timeattribute',
            name='name',
        ),
        migrations.RemoveField(
            model_name='travelattribute',
            name='name',
        ),
    ]
