# Generated by Django 4.1.8 on 2023-05-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0011_remove_booleanattribute_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleanattribute',
            name='in_summary',
        ),
        migrations.RemoveField(
            model_name='floatattribute',
            name='in_summary',
        ),
        migrations.RemoveField(
            model_name='integerattribute',
            name='in_summary',
        ),
        migrations.RemoveField(
            model_name='stringattribute',
            name='in_summary',
        ),
        migrations.RemoveField(
            model_name='timeattribute',
            name='in_summary',
        ),
        migrations.RemoveField(
            model_name='travelattribute',
            name='in_summary',
        ),
    ]
