# Generated by Django 4.1.8 on 2023-05-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0012_remove_booleanattribute_in_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributemodule',
            name='field_type',
            field=models.CharField(choices=[('BoA', 'booleanAttribute'), ('TiA', 'timeAttribute'), ('InA', 'integerAttribute'), ('FlA', 'floatAttribute'), ('StA', 'stringAttribute'), ('TrA', 'travelAttribute')], default='InA', max_length=3),
        ),
    ]
