# Generated by Django 4.1.8 on 2023-05-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0013_alter_attributemodule_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelattribute',
            name='type_field',
            field=models.CharField(blank=True, choices=[('T', 'Öffis'), ('B', 'Reisebus'), ('C', 'PKW'), ('O', 'Sonstiges')], max_length=1, null=True),
        ),
    ]
