# Generated by Django 4.2.2 on 2023-08-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registrationrating'),
        ('attributes', '0014_alter_travelattribute_type_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeAttribute',
            new_name='DateTimeAttribute',
        ),
        migrations.RenameField(
            model_name='datetimeattribute',
            old_name='date_field',
            new_name='date_time_field',
        ),
        migrations.AlterField(
            model_name='attributemodule',
            name='field_type',
            field=models.CharField(choices=[('BoA', 'booleanAttribute'), ('TiA', 'dateTimeAttribute'), ('InA', 'integerAttribute'), ('FlA', 'floatAttribute'), ('StA', 'stringAttribute'), ('TrA', 'travelAttribute')], default='InA', max_length=3),
        ),
    ]
