# Generated by Django 4.1.13 on 2024-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0015_rename_timeattribute_datetimeattribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributemodule',
            name='text',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
