# Generated by Django 4.1.8 on 2023-05-04 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('free_text', models.CharField(blank=True, max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('min_person', models.IntegerField(blank=True, null=True)),
                ('max_person', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('w', 'Workshop'), ('e', 'Excursion'), ('l', 'Vortrag'), ('p', 'Aufführung'), ('d', 'Diskussionsrunde'), ('r', 'Lesung')], default='w', max_length=1)),
                ('duration', models.IntegerField(default=60)),
                ('can_be_repeated', models.BooleanField(default=False)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkshopParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.registrationparticipant')),
                ('workshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
