# Generated by Django 4.1.5 on 2023-01-28 20:02

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keycloak_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('public', models.BooleanField(default=False)),
                ('question', models.TextField(blank=True, max_length=250, null=True)),
                ('answer', models.TextField(blank=True, max_length=10000, null=True)),
                ('type', models.CharField(choices=[('FAQ', 'FAQ'), ('P', 'Datenschutz')], default='FAQ', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EatHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FrontendTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=100)),
                ('primary', colorfield.fields.ColorField(default='#1976D2', image_field=None, max_length=18, samples=None)),
                ('secondary', colorfield.fields.ColorField(default='#424242', image_field=None, max_length=18, samples=None)),
                ('accent', colorfield.fields.ColorField(default='#82B1FF', image_field=None, max_length=18, samples=None)),
                ('error', colorfield.fields.ColorField(default='#FF5252', image_field=None, max_length=18, samples=None)),
                ('info', colorfield.fields.ColorField(default='#2196F3', image_field=None, max_length=18, samples=None)),
                ('success', colorfield.fields.ColorField(default='#4CAF50', image_field=None, max_length=18, samples=None)),
                ('warning', colorfield.fields.ColorField(default='#FFC107', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutOrgaLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=9999)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=5)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('lat', models.DecimalField(decimal_places=15, default=0.0, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=15, default=0.0, max_digits=20)),
                ('state', models.CharField(choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hessen'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thüringen')], default='BY', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.tagtype')),
            ],
        ),
        migrations.CreateModel(
            name='ScoutHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('level_choice', models.CharField(choices=[('Verband', 'Verband'), ('Bund', 'Bund'), ('Ring', 'Ring/Regional'), ('Stamm', 'Stamm'), ('Gruppe', 'Gruppe'), ('Scout', 'Pfadfinder*innen')], default='Gruppe', max_length=10)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('abbreviation', models.CharField(blank=True, max_length=5, null=True)),
                ('keycloak', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keycloak_auth.keycloakgroup')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.scoutorgalevel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scouthierarchy', to='basic.scouthierarchy')),
                ('zip_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.zipcode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
