# Generated by Django 4.1.2 on 2022-10-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouthierarchy',
            name='keycloak_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
