# Generated by Django 4.1.9 on 2023-06-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0004_alter_keycloakgroup_membership_allowed'),
        ('basic', '0002_eathabit_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouthierarchy',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scouthierarchy',
            name='keycloak',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keycloak_auth.keycloakgroup'),
        ),
    ]
