# Generated by Django 4.1.2 on 2022-10-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('basic', '0002_scouthierarchy_keycloak_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouthierarchy',
            name='level_choice',
            field=models.CharField(
                choices=[
                    ('Verband', 'Verband'),
                    ('Bund', 'Bund'),
                    ('Ring', 'Ring/Regional'),
                    ('Stamm', 'Stamm'),
                    ('Gruppe', 'Gruppe'),
                    ('Scout', 'Pfadfinder*innen')
                ],
                default='Gruppe',
                max_length=10),
        ),
    ]
