# Generated by Django 4.1.9 on 2023-08-18 17:27

from django.db import migrations
from basic.helper.initialize_keycloak_scout_hierarchies import InitKeycloakScoutHierarchies
from basic.helper.sync_keycloak_groups import SyncKeycloakGroups

def init_scout_hierarchies(apps, schema_editor):
    InitKeycloakScoutHierarchies().run()
    SyncKeycloakGroups().run()

class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_scouthierarchy_full_name_and_more'),
    ]

    operations = [
        migrations.RunPython(init_scout_hierarchies)
    ]
