# Generated by Django 4.1.2 on 2022-10-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0001_initial'),
        ('basic', '0003_scouthierarchy_level_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scouthierarchy',
            name='keycloak_id',
        ),
        migrations.AddField(
            model_name='scouthierarchy',
            name='keycloak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keycloak_auth.keycloakgroup'),
        ),
    ]
