# Generated by Django 4.1.3 on 2022-11-08 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0002_alter_keycloakgroup_keycloak_id_and_more'),
        ('basic', '0004_remove_scouthierarchy_keycloak_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scouthierarchy',
            name='keycloak',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keycloak_auth.keycloakgroup'),
        ),
    ]
