# Generated by Django 4.0.6 on 2022-09-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price_per_kg',
            field=models.FloatField(default=0),
        ),
    ]
