# Generated by Django 4.1.7 on 2023-03-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_pollitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollitem",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="package_winner",
                to="food.package",
            ),
        ),
    ]
