# Generated by Django 4.0.6 on 2022-09-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_package_price_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='portion',
            name='price_per_kg',
            field=models.FloatField(default=0),
        ),
    ]
