# Generated by Django 4.2.2 on 2023-06-25 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0024_eventmodule_description'),
        ('food', '0003_alter_pollitem_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('norm_portions', models.IntegerField()),
                ('reserve_factor', models.FloatField(default=1.0)),
                ('is_public', models.BooleanField(default=False)),
                ('activity_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food.physicalactivitylevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_event_created_by', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='mealday',
            name='event',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Frühstück'), ('lunch_warm', 'Menu (warm)'), ('lunch_cold', 'Menu (kalt)'), ('dessert', 'Nachtisch'), ('snack', 'Snack')], default='lunch_warm', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Frühstück'), ('lunch_warm', 'Menu (warm)'), ('lunch_cold', 'Menu (kalt)'), ('dessert', 'Nachtisch'), ('snack', 'Snack')], default='lunch_warm', max_length=11),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='mealday',
            name='meal_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.mealevent'),
        ),
    ]
