# Generated by Django 4.2.2 on 2023-07-15 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0005_recipe_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealday',
            old_name='activity_facor',
            new_name='activity_factor',
        ),
        migrations.AddField(
            model_name='mealevent',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mealevent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='mealevent',
            name='created_by',
        ),
        migrations.AddField(
            model_name='mealevent',
            name='created_by',
            field=models.ManyToManyField(blank=True, related_name='meal_event_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
