# Generated by Django 4.0.6 on 2022-09-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_recipeitem_price_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
