# Generated by Django 4.2.2 on 2023-07-16 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0006_rename_activity_facor_mealday_activity_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_by',
            field=models.ManyToManyField(blank=True, related_name='recipe_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
