# Generated by Django 4.0.6 on 2022-09-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_recipeitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
