# Generated by Django 4.0.6 on 2022-09-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_recipeitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
