# Generated by Django 4.0.6 on 2022-11-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_recipe_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='portion',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='nutri_points_sodium_mg',
            new_name='nutri_points_salt_g',
        ),
        migrations.RenameField(
            model_name='recipeitem',
            old_name='nutri_points_sodium_mg',
            new_name='nutri_points_salt_g',
        ),
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('simulator', 'Simulator'), ('verified', 'Verified'), ('user', 'User')], default='simulator', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='portion',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='hints',
            field=models.ManyToManyField(blank=True, null=True, to='food.hint'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='portion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='food.portion'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='food.recipe'),
        ),
    ]
