# Generated by Django 4.1.9 on 2023-10-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_meal_is_public_meal_time_end_meal_time_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealday',
            name='activity_factor',
        ),
    ]
