# Generated by Django 4.1.9 on 2023-10-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_remove_mealday_activity_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Frühstück'), ('lunch_warm', 'Menu (warm)'), ('lunch_cold', 'Menu (kalt)'), ('dessert', 'Nachtisch'), ('snack', 'Snack'), ('drink', 'Getränk')], default='lunch_warm', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Frühstück'), ('lunch_warm', 'Menu (warm)'), ('lunch_cold', 'Menu (kalt)'), ('dessert', 'Nachtisch'), ('snack', 'Snack'), ('drink', 'Getränk')], default='lunch_warm', max_length=11),
        ),
    ]
