# Generated by Django 4.0.6 on 2022-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_package_options_alter_portion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='nutri_points_sodium_mg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='nutri_points_sodium_mg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='hints',
            field=models.ManyToManyField(blank=True, to='food.hint'),
        ),
    ]
