# Generated by Django 4.0.6 on 2022-11-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_ingredient_nutri_points_sodium_mg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrate_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='energy_kj',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_sat_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fibre_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fructose_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='lactose_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='salt_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodium_mg',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sugar_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='carbohydrate_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='energy_kj',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='fat_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='fat_sat_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='fibre_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='fructose_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='lactose_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='protein_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='salt_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='sodium_mg',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='sugar_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbohydrate_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='energy_kj',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat_sat_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fibre_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fructose_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='lactose_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='salt_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sodium_mg',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sugar_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='carbohydrate_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='energy_kj',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='fat_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='fat_sat_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='fibre_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='fructose_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='lactose_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='protein_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='salt_g',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='sodium_mg',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='sugar_g',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
