# Generated by Django 4.1.2 on 2022-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0012_alter_ingredient_carbohydrate_g_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="price_per_kg",
            field=models.FloatField(default=0),
        ),
    ]
