# Generated by Django 4.1.2 on 2022-12-04 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0015_rename_mealday_meal_meal_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealitem",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="food.meal"
            ),
        ),
    ]
