# Generated by Django 4.1.2 on 2022-12-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0016_alter_mealitem_meal"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalActivityLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("value", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="meal",
            old_name="factor",
            new_name="day_part_factor",
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mealday",
            name="max_day_part_factor",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="major_class",
            field=models.CharField(
                choices=[
                    ("Baked Products", "Backwaren"),
                    ("Beef Products", "Ringfleisch"),
                    ("Beverages", "Getränk"),
                    ("Cereal Grains and Pasta", "Nudeln und Getreide "),
                    ("Dairy and Egg Products", "Milch und Ei"),
                    ("Fats and Oils", "Fette und and Öl"),
                    ("Finfish and Shellfish Products", "Meeresfrücht und Fisch"),
                    ("Fruits and Fruit Juices", "Früchte"),
                    ("Legumes and Legume Products", "Hülsenfrüchte"),
                    ("Nut and Seed Products", "Nuß und Samen"),
                    ("Pork Products", "Schweinefleisch"),
                    ("Poultry Products", "Geflügel"),
                    ("Sausages and Luncheon Meats", "Wurst"),
                    ("Soups, Sauces, and Gravies", "Suppe oder Soße"),
                    ("Spices and Herbs", "Gewürz"),
                    ("Sweets", "Süßigkeit"),
                    ("Vegetables and Vegetable Products", "Gemüse"),
                    ("undefined", "unbekannt"),
                ],
                default="undefined",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Frühstück"),
                    ("lunch_warm", "Menu (warn)"),
                    ("lunch_cold", "Menu (kalt)"),
                    ("snack", "Snack"),
                ],
                default="lunch_warm",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mealday",
            name="event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="food.event"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Frühstück"),
                    ("lunch_warm", "Menu (warn)"),
                    ("lunch_cold", "Menu (kalt)"),
                    ("snack", "Snack"),
                ],
                default="lunch_warm",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="status",
            field=models.CharField(
                choices=[
                    ("simulator", "Simulator"),
                    ("verified", "Verified by Inspi"),
                    ("user_conent", "Benutzer erstellt"),
                    ("user_public", "Benutzer Öffentlich"),
                ],
                default="simulator",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="activity_facor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="food.physicalactivitylevel",
            ),
        ),
        migrations.AlterField(
            model_name="mealday",
            name="activity_facor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="food.physicalactivitylevel",
            ),
        ),
    ]
