# Generated by Django 4.1.2 on 2022-12-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0018_rename_activity_facor_event_activity_factor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="activity_factor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="food.physicalactivitylevel",
            ),
        ),
    ]
