# Generated by Django 4.1.5 on 2023-01-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_alter_event_activity_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
