# Generated by Django 4.1.2 on 2023-01-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0020_alter_hint_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="price_per_kg",
        ),
    ]
