# Generated by Django 4.1.2 on 2023-01-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0022_remove_portion_price_per_kg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="price_per_kg",
        ),
    ]
