# Generated by Django 4.1.2 on 2023-01-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0023_remove_ingredient_price_per_kg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="price_per_kg",
        ),
        migrations.RemoveField(
            model_name="recipeitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="recipeitem",
            name="price_per_kg",
        ),
    ]
