# Generated by Django 4.1.5 on 2023-01-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_remove_recipe_price_per_kg_remove_recipeitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='price',
        ),
    ]
